version: 0.2

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Derive VERSION_TAG robustly:
      # 1) If webhook triggered by a tag push -> tag/<ver>
      # 2) Else use CODEBUILD_SOURCE_VERSION or CODEBUILD_RESOLVED_SOURCE_VERSION (may be refs/tags/<ver>)
      - RAW_TRIGGER="${CODEBUILD_WEBHOOK_TRIGGER:-}"
      - RAW_SRC="${CODEBUILD_SOURCE_VERSION:-${CODEBUILD_RESOLVED_SOURCE_VERSION:-}}"
      - if [[ "$RAW_TRIGGER" == tag/* ]]; then VERSION_TAG="${RAW_TRIGGER#tag/}"; \
        elif [[ "$RAW_SRC" == refs/tags/* ]]; then VERSION_TAG="${RAW_SRC#refs/tags/}"; \
        else VERSION_TAG="latest"; fi
      - echo "VERSION_TAG resolved to: $VERSION_TAG"

  build:
    commands:
      - echo "Building image..."
      - docker build -t hbcd .

      # Tag for Docker Hub
      - IMAGE_REPO="$DOCKERHUB_USERNAME/hbcd-made"
      - docker tag hbcd "$IMAGE_REPO:latest"
      - if [[ "$VERSION_TAG" != "latest" ]]; then docker tag hbcd "$IMAGE_REPO:$VERSION_TAG"; fi

  post_build:
    commands:
      - echo "Pushing images..."
      - docker push "$IMAGE_REPO:latest"
      - if [[ "$VERSION_TAG" != "latest" ]]; then docker push "$IMAGE_REPO:$VERSION_TAG"; fi
