name: ci

on:
  push:
    branches:
      - main
    # Any tag
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "dcanumn/dcan-cloud-builder-1"

      # Dynamically build up the list of image tags
      - name: Determine Docker Image Tags
        id: vars
        run: |
          # Always include "latest"
          echo "tags=dcanumn/hbcd-made:latest" >> $GITHUB_OUTPUT

          # If this is a tag push (refs/tags/1.2.3, for example),
          # also add "dcanumn/hbcd-made:1.2.3"
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            echo "tags=${{ steps.vars.outputs.tags }},dcanumn/hbcd-made:${VERSION_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.vars.outputs.tags }}
          # Keep your existing logic for pull requests vs. pushes
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
